// <auto-generated />
namespace RPA.MTSInspections.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Weighting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Weighting));
        
        string IMigrationMetadata.Id
        {
            get { return "201804031337115_Weighting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
